### ISSUE TITLE
Pan-domain authentication required?

### ISSUE THREAD

**Issue by gordonclarkok** [guardian/grid#1116]
Hello,
We have installed the grid platform & have all the required AWS users/roles/s3 buckets etc configured.

When hitting the media-api endpoint with a simple curl, we are getting the following:

<pre>
[info] application - Checking alias imagesAlias is assigned to index…
[info] o.e.plugins - [Dreadnought] loaded [], sites []
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[error] application -

! @6n7hnl96h - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[ExceptionInInitializerError: null]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:170) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.8.jar:2.3.8]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.8.jar:2.3.8]
Caused by: java.lang.ExceptionInInitializerError: null
	at Global$.onStart(Global.scala:19) ~[na:na]
	at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.6.jar:na]
<b>Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential. (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: 1B33F7093F0BE82F) </b>
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1078) ~[aws-java-sdk-core-1.9.24.jar:na]
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:726) ~[aws-java-sdk-core-1.9.24.jar:na]
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461) ~[aws-java-sdk-core-1.9.24.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:296) ~[aws-java-sdk-core-1.9.24.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3735) ~[aws-java-sdk-s3-1.9.24.jar:na]
</pre>

Looking at other issues it seems we may have to install pan-domain authentication - is this definitely required?

Regards,
Gordon

**Comment by kenoir** [comment]
This doesn't look like a pan domain auth problem to me rather an AWS auth config issue.

**Comment by theefer** [comment]
Is it missing a `panda.aws.key/secret` in `/etc/gu/panda.properties` perhaps?

But yes, you will need to setup a configuration for pan-domain-auth [as described in this other issue](https://github.com/guardian/grid/issues/1081#issuecomment-132780670). This is currently a requirement as the APIs need auths. In theory it could be adapted to support custom auth providers others than Google though.

**Comment by kenoir** [comment]
^ `a non-empty Access Key (AKID)` probably the key is missing I would guess.

**Comment by gordonclarkok** [comment]
Hello,
Thanks very much for your prompt & detailed replies.

Indeed I was missing the values in ```/etc/gu/panda.properties``` - hence the missing key error I presume.

I'm now getting the same ```Access Denied``` error as in Issue #1081 so I guess this can be marked as a duplicate?

I'll follow the steps as detailed in the other issue.

Thanks again,
Gordon

**Comment by kenoir** [comment]
Closing. @gordonclarkok let us know if you get stuck again in another issue and we'll try and help.

**Comment by akash1810** [comment]
Quite a late response... #2927 looks like it'll help here. Would be interested to get your feedback on it.
