### ISSUE TITLE
Error generating dot_properties

### ISSUE THREAD

**Issue by comeback-techie** [guardian/grid#1907]
I'm trying to setup grid app locally on my ubuntu 14.04 vm. The following are the steps I followed:
Installed/Cloned/Downloaded
java, sbt, git, nginx, exiftool, jq, awscli, pip, guardian grid

Configured
java
- set JAVA_HOME
- added JAVA_HOME to environment

awscli 
- generated aws key and secret key by creating IAM user Sarma using
  AWS credentials of Kiran Lanka
- aws configure profile media-service, 
- exported it to .profile,
- set it as default aws profile 

nginx
- created host hydlocal.in in hosts file
- created sub-domains grid.hydlocal.in and api.grid.hydlocal.in
- generated self-signed local ssl certificates for these domains
- added conf file under sites-available to add server, port, ssl and
  location for the subdomain 

Elasticsearch
- ran elasticsearch installer
- start elasticsearch

Cloud Formation
- created dev stack that resulted in:
  - creating new user under IAM service with media-service-DEV-user
  - creating new dev stack under cloudformation service with 
    media-service-DEV-
  - creating s3 buckets required for Grid app with their respective
    policies:
         - Image, ImageOrigin, ImageCollection
         - Collection, Key, Leases, Thumb, Topic
         - Indexed Image Metadata, S3Watcher, Usage

Now, when trying to generate the dot_properties as per README, I am getting below error. 

root@brns-VirtualBox:~/grid/grid/docker/configs/generators# python -m generators.dot_properties /etc/gu
2016-05-25 12:09:53,305 dot_properties INFO Start
2016-05-25 12:09:53,325 cloudformation INFO Using AWS profile media-service
2016-05-25 12:09:53,489 botocore.credentials INFO Found credentials in shared credentials file: ~/.aws/credentials
2016-05-25 12:09:53,660 boto3.resources.action INFO Calling iam:get_user with {}
2016-05-25 12:09:53,668 botocore.vendored.requests.packages.urllib3.connectionpool INFO Starting new HTTPS connection (1): iam.amazonaws.com
2016-05-25 12:09:54,956 cloudformation INFO Using stack media-service-DEV-Sarma
2016-05-25 12:09:55,030 botocore.vendored.requests.packages.urllib3.connectionpool INFO Starting new HTTPS connection (1): cloudformation.us-west-2.amazonaws.com
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/grid/grid/docker/configs/generators/generators/dot_properties.py", line 50, in <module>
    generate(output_dir)
  File "/root/grid/grid/docker/configs/generators/generators/dot_properties.py", line 43, in generate
    generate_files(directory, config.get('properties'))
  File "/root/grid/grid/docker/configs/generators/generators/dot_properties.py", line 24, in generate_files
    stack_output = get_stack_outputs()
  File "generators/cloudformation.py", line 33, in get_stack_outputs
    stack = cf_client.describe_stacks(StackName=stack_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 301, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 398, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id media-service-DEV-Sarma does not exist

The steps I followed to get the above error are:
1. pip install -r requirements.txt under /root/grid/grid/docker/configs/generators
2. created venv under root/grid/grid
3. created grid-settings.yml file under root/.gu/grid
4. ran generate-dot-properties.sh

What am I doing wrong here? Are the steps I am following are correct?

**Comment by NickPapacostas** [comment]
Heyo,

Thanks for the thorough description of your problem!

I think the issue here is related to the creation of your dev stack in AWS. You'll notice that [create-dev-stack.sh](https://github.com/guardian/grid/blob/master/cloud-formation/scripts/create-dev-stack.sh) calls [stack_name.sh](https://github.com/guardian/grid/blob/master/cloud-formation/scripts/stack-name.sh). Create-dev-stack needs to create a stack called "media-service-DEV-YOUR_USERNAME" , whereas you can see that yours is missing the "YOUR_USERNAME" part.
> creating new dev stack under cloudformation service with media-service-DEV-

So when you try to generate your dot-properties, it can't find "media-service-DEV-Sarma".

We've changed this a bit recently to focus on our internal process which is why you're having trouble. 

The solution is to:

1. delete the "media-service-DEV-" stack in your AWS account. 
2. write the string ``` media-service-DEV-Sarma  ``` to "~/.gu/grid/dev_stack_name" (https://github.com/guardian/grid/blob/master/cloud-formation/scripts/stack-name.sh#L3)
3. re-run ./create-dev-stack.sh
4. re-run the dot-properties geneartors. 

I'll work on a change to make this clearer for folks in the future. 

Let us know how that works out for you!

Thanks for getting in touch,
Nick & The Grid team

**Comment by comeback-techie** [comment]
Thanks for quick response. I tried the steps suggested however it is not working. Surely somewhere I am going wrong since I am new to linux and github too. Can you please clarify a question..now don't laugh at me...is this folder "~/.gu/grid" should be created by me? What I did is I created this folder and then created this file dev_stack_name with media-service-DEV-Sarma written into it. Is this correct? If so then the your suggested solution did not work for me. If not please let me know how to go about.

I am sitting on this app since 10 days and still could as much run the services and access at least one of 'em from my browser.

**Comment by NickPapacostas** [comment]
Hey again,

What you did sounds correct. I'm not sure why that didn't work, are you getting the same exact errors? If not could you send us a stack trace?

**Comment by comeback-techie** [comment]
Correct.. i got the same error. I'm taking up a new vm and try to repeat the whole process from scratch. I'll get back with result. 

Can you clarify one more point please - is the /etc/gu folder is created by build process or manually? If through build process at which step of the entire setup / installation process such creation or by running which script?

**Comment by comeback-techie** [comment]
Ok..finally I got through that issue with dev stack but now hit another roadblock when run generate-dot-properties 

creating a virtualenv
./generate-dot-properties.sh: line 13: virtualenv: command not found
./generate-dot-properties.sh: line 16: .venv/bin/activate: No such file or directory
creating dot-properties to /etc/gu
2016-05-27 16:46:31,769 dot_properties INFO Start
2016-05-27 16:46:31,778 cloudformation INFO Using AWS profile media-service
2016-05-27 16:46:31,784 cloudformation INFO Using stack media-service-DEV-brns
2016-05-27 16:46:31,789 botocore.credentials INFO Credentials found in config file: ~/.aws/config
2016-05-27 16:46:31,853 botocore.vendored.requests.packages.urllib3.connectionpool INFO Starting new HTTPS connection (1): cloudformation.us-west-2.amazonaws.com
2016-05-27 16:46:33,646 cloudformation INFO Here is your CloudFormation Stack output
2016-05-27 16:46:33,646 cloudformation INFO AwsId = ***censored***
2016-05-27 16:46:33,647 cloudformation INFO AwsSecret = ***censored***
2016-05-27 16:46:33,648 cloudformation INFO ImageBucket = media-service-dev-brns-imagebucket-induhsia1f75
2016-05-27 16:46:33,648 cloudformation INFO ThumbBucket = media-service-dev-brns-thumbbucket-e5ggxm9nnzsp
2016-05-27 16:46:33,648 cloudformation INFO KeyBucket = media-service-dev-brns-keybucket-lcit9koq4iqa
2016-05-27 16:46:33,649 cloudformation INFO ImageOriginBucket = media-service-dev-brns-imageoriginbucket-1n34e6yiuwmu2
2016-05-27 16:46:33,649 cloudformation INFO ImageOriginWebsite = media-service-dev-brns-imageoriginbucket-1n34e6yiuwmu2.s3-website-us-west-2.amazonaws.com
2016-05-27 16:46:33,650 cloudformation INFO ConfigBucket = media-service-dev-brns-configbucket-1flw4ct7hhlt0
2016-05-27 16:46:33,650 cloudformation INFO CollectionsBucket = media-service-dev-brns-collectionsbucket-1ofij23uypwpa
2016-05-27 16:46:33,651 cloudformation INFO S3WatcherIngestBucket = media-service-dev-brns-s3watcheringestbucket-h2blypr7fooe
2016-05-27 16:46:33,651 cloudformation INFO S3WatcherFailBucket = media-service-dev-brns-s3watcherfailbucket-182ep513yijm4
2016-05-27 16:46:33,651 cloudformation INFO EditsDynamoTable = media-service-DEV-brns-EditsDynamoTable-1U2Q2UW56P5BS
2016-05-27 16:46:33,652 cloudformation INFO CollectionsDynamoTable = media-service-DEV-brns-CollectionsDynamoTable-1OZ0HKW9548QO
2016-05-27 16:46:33,652 cloudformation INFO ImageCollectionsDynamoTable = media-service-DEV-brns-ImageCollectionsDynamoTable-QNQB78N8E7MC
2016-05-27 16:46:33,653 cloudformation INFO LeasesDynamoTable = media-service-DEV-brns-LeasesDynamoTable-1T1EM72B97GZ4
2016-05-27 16:46:33,653 cloudformation INFO SnsTopicArn = arn:aws:sns:us-west-2:008862036995:media-service-DEV-brns-Topic-4PF9AFIY8SJP
2016-05-27 16:46:33,654 cloudformation INFO SqsQueueUrl = https://sqs.us-west-2.amazonaws.com/008862036995/media-service-DEV-brns-Queue-NZ0TMWAXKEVQ
2016-05-27 16:46:33,654 cloudformation INFO IndexedImageTopicArn = arn:aws:sns:us-west-2:008862036995:media-service-DEV-brns-IndexedImageTopic-365V5SC61PA4
2016-05-27 16:46:33,654 cloudformation INFO IndexedImageMetadataQueueUrl = https://sqs.us-west-2.amazonaws.com/008862036995/media-service-DEV-brns-IndexedImageMetadataQueue-ENGGDKH004IX
2016-05-27 16:46:33,655 cloudformation INFO UsageRecordTable = media-service-DEV-brns-UsageRecordTable-1H6ZYYBT8BCPZ
2016-05-27 16:46:33,656 cloudformation INFO LiveContentPollTable = media-service-DEV-brns-LiveContentPollTable-BEPQUN60H7NS
2016-05-27 16:46:33,656 cloudformation INFO PreviewContentPollTable = media-service-DEV-brns-PreviewContentPollTable-11F36FX75PILY
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/grid/docker/configs/generators/generators/dot_properties.py", line 50, in <module>
    generate(output_dir)
  File "/root/grid/docker/configs/generators/generators/dot_properties.py", line 43, in generate
    generate_files(directory, config.get('properties'))
  File "/root/grid/docker/configs/generators/generators/dot_properties.py", line 25, in generate_files
    [stack_output.update(prop) for prop in config_properties]
ValueError: dictionary update sequence element #0 has length 1; 2 is required

Any idea?

**Comment by akash1810** [comment]
Hi @comeback-techie,

Thanks for using Grid!

> Can you clarify one more point please - is the /etc/gu folder is created by build process or manually?

I've just realised a problem in our scripts, which I've raised a PR to fix - #1913.

Grid services use `/etc/gu` for configuration. The `/etc` directory is owned by the root user. The generate scripts [creates directories](https://github.com/guardian/grid/blob/master/docker/configs/generators/generators/__init__.py#L38) that don't already exist.

The problem arises if you run the generate script to output to `/etc/gu` as a normal user as you won't have write access. There are two solutions to this:

1. Run the generator as sudo `sudo ./generate-dot-properties.sh`, or
2. Change ownership of `/etc/gu` to the current user, then run `./generate-dot-properties.sh` as normal:
   
    `sudo chown -R $(whoami) /etc/gu`

The second solution is what we tend to use.

I've [updated](https://github.com/guardian/grid/tree/aa-clearer-readme/docker/configs/generators) the README to hopefully make the process simpler.

Regarding these messages in your stack trace:

> ./generate-dot-properties.sh: line 13: virtualenv: command not found
./generate-dot-properties.sh: line 16: .venv/bin/activate: No such file or directory

This is because the `virtualenv` package is not installed - the requirements in the [readme have been updated](https://github.com/guardian/grid/tree/aa-clearer-readme/docker/configs/generators) too to reflect this.

Please let us know how you get on.

**Comment by comeback-techie** [comment]
Hi akash1810

Regarding /etc/gu - I knew I need to run ./generate-dot-properties.sh as sudo. What I don't know is if it generaetd as part of app build process or I should create these manually. Thanks for clarifying on this.

Regarding my stack trace - after I install virtualenv package, which I did during my previous setup trials, it resulted in error with aws cli(some Not Type / Type error - I could'nt remember it exactly) and forcing me to create fresh environment all over again. When I googled the issue I got some responses stating it is the result of compatibility issues of aws cli with virtualenv.  I'll get back on this error in detail.

After all this, my issue 'ValueError: dictionary update sequence element #0 has length 1; 2 is required' still persists.

**Comment by comeback-techie** [comment]
Ok.  this is the error I get when I use any aws cli command or ./create_dev_stack after virtualenv is installed:

Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 50, in main
    return driver.main()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 176, in main
    parser = self._create_parser()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 157, in _create_parser
    command_table = self._get_command_table()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 91, in _get_command_table
    self._command_table = self._build_command_table()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 111, in _build_command_table
    command_object=self)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 675, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/preview.py", line 71, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 349, in service_model
    return self._get_service_model()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 366, in _get_service_model
    api_version = self.session.get_config_variable('api_versions').get(
AttributeError: 'NoneType' object has no attribute 'get'

Now I have to take a fresh vm and start all over agian. 

Meanwhile any idea on error "ValueError: dictionary update sequence element #0 has length 1; 2 is required"?

**Comment by akash1810** [comment]
hi @comeback-techie,

We've identified the issue you were seeing when using the awscli in a virtualenv - it boils down to package versioning and is fixed in https://github.com/guardian/grid/pull/1916.

Please pull from master and run `pip install -r requirements.txt` again and try running the generator again.

Thanks for your patience and feedback.

**Comment by nmpdcafe** [comment]
Hi, I resurrect this thread because I went pretty much as far as comeback-techie and hit the same error while running "./generate-dot-properties.sh /etc/gu" (that I run as root) : 

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/cafe/grid-master/docker/configs/generators/generators/dot_properties.py", line 50, in <module>
    generate(output_dir)
  File "/home/cafe/grid-master/docker/configs/generators/generators/dot_properties.py", line 43, in generate
    generate_files(directory, config.get('properties'))
  File "/home/cafe/grid-master/docker/configs/generators/generators/dot_properties.py", line 25, in generate_files
    [stack_output.update(prop) for prop in config_properties]
ValueError: dictionary update sequence element #0 has length 1; 2 is required

Does anyone has a solution to this error ?

**Comment by akash1810** [comment]
We've since moved to a javascript implementation for property generation (https://github.com/guardian/grid/pull/2103). Closing this issue. Please open a new one if you encounter issues.
