### ISSUE TITLE
Error generation configuration files 

### ISSUE THREAD

**Issue by bobok** [guardian/grid#2417]
Ubuntu 18.04 

./generate-dot-properties.js 
(node:27728) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tracking' of undefined
    at getKahunaConfig (/home/grid/scripts/generate-dot-properties/service-config.js:59:45)
    at Object.getConfigs (/home/grid/scripts/generate-dot-properties/service-config.js:151:21)
    at /home/grid/scripts/generate-dot-properties/generate-dot-properties.js:45:42
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:27728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mbarton** [comment]
Hi Bobok. I can run that script successfully locally, do you still have the Google tracking ID section of your `config.json5` file?

https://github.com/guardian/grid/blob/master/scripts/generate-dot-properties/config.json5#L49

**Comment by akash1810** [comment]
Closing as no recent activity.
