### ISSUE TITLE
Cropping fails on some images with unknown colour profiles

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/grid#822]
Here's an example: https://media.test.dev-gutools.co.uk/images/f811260a1522d8672db831b314c0332fe512917e/crop

Here's the error:
```
play.api.Application$$anon$1: Execution exception[[CommandException: org.im4java.core.CommandException: convert convert: Unable to assign profile (Colorspace color profile mismatch).]]
	at play.api.Application$class.handleError(Application.scala:296) ~[app.jar:0.1]
	at play.api.DefaultApplication.handleError(Application.scala:402) [app.jar:0.1]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [app.jar:0.1]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [app.jar:0.1]
	at scala.Option.map(Option.scala:146) [app.jar:0.1]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [app.jar:0.1]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [app.jar:0.1]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [app.jar:0.1]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [app.jar:0.1]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [app.jar:0.1]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [app.jar:0.1]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [app.jar:0.1]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [app.jar:0.1]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [app.jar:0.1]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [app.jar:0.1]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [app.jar:0.1]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [app.jar:0.1]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [app.jar:0.1]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [app.jar:0.1]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [app.jar:0.1]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [app.jar:0.1]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [app.jar:0.1]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [app.jar:0.1]
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [app.jar:0.1]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [app.jar:0.1]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401) [app.jar:0.1]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [app.jar:0.1]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [app.jar:0.1]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [app.jar:0.1]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [app.jar:0.1]
Caused by: org.im4java.core.CommandException: org.im4java.core.CommandException: convert convert: Unable to assign profile (Colorspace color profile mismatch).
	at org.im4java.core.ImageCommand.run(ImageCommand.java:219) ~[app.jar:0.1]
	at lib.imaging.im4jwrapper.ImageMagick$$anonfun$runConvertCmd$1.apply$mcV$sp(ImageMagick.scala:26) ~[app.jar:0.1]
	at lib.imaging.im4jwrapper.ImageMagick$$anonfun$runConvertCmd$1.apply(ImageMagick.scala:26) ~[app.jar:0.1]
	at lib.imaging.im4jwrapper.ImageMagick$$anonfun$runConvertCmd$1.apply(ImageMagick.scala:26) ~[app.jar:0.1]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[app.jar:0.1]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[app.jar:0.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
Caused by: org.im4java.core.CommandException: convert convert: Unable to assign profile (Colorspace color profile mismatch).
	at org.im4java.core.ImageCommand.finished(ImageCommand.java:253) ~[app.jar:0.1]
	at org.im4java.process.ProcessStarter.run(ProcessStarter.java:314) ~[app.jar:0.1]
	at org.im4java.core.ImageCommand.run(ImageCommand.java:215) ~[app.jar:0.1]
	... 8 common frames omitted
```

**Comment by jamesgorrie** [comment]
@theefer Was this fixed?

**Comment by theefer** [comment]
It should be.
